### ISSUE TITLE
i didnt find the evaluation code for llama

### ISSUE THREAD

**Issue by lucywang720** [waterhorse1/ChessGPT#4]
sry but is there any?

**Comment by waterhorse1** [comment]
check this: https://github.com/waterhorse1/ChessGPT/tree/main/eval/eval_gpt

**Comment by lucywang720** [comment]
Thank you! So the prompt you use is in https://github.com/waterhorse1/ChessGPT/tree/main/eval/eval_gpt/test.json

**Comment by waterhorse1** [comment]
This is just an example, please refer to the readme for a detailed illustration.
